# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory to /app inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if present) to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose port 5001 (the port the app runs on)
EXPOSE 5001

# Define the command to run the application
CMD [ "node", "source/app.js" ]
