.PHONY: gen watch clean-gen

# Chạy build_runner một lần
gen:
	@echo "Lưu ý: Đang chạy build_runner..."
	@dart run build_runner build --delete-conflicting-outputs

# Chạy build_runner ở chế độ theo dõi (watch mode)
watch:
	@dart run build_runner watch --delete-conflicting-outputs